name: Production deploy
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to deploy to prod"
        default: "latest"
        required: false
        type: string
  workflow_call:
jobs:
  call_deploy:
    name: Call Deploy prod via ssh
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
    secrets:
      DEPLOY_HOST: "${{ secrets.PROD_DEPLOY_HOST }}"
      DEPLOY_USERNAME: "${{ secrets.PROD_DEPLOY_USERNAME }}"
      DEPLOY_KEY: "${{ secrets.PROD_DEPLOY_KEY }}"
